spring.application.name=gecko
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.com.bhav.gecko=DEBUG
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n
spring.output.ansi.enabled=ALWAYS

# Keeping the threshold 10MB
memtable.flsuh.threshold = 10485760

wal.directory=./wal_data
# Interval in milliseconds for the background thread to force sync the WAL to physical disk
wal.sync.interval.ms=200
sst.directory=./sst

# Read cache
read.cache.enabled=true
read.cache.capacity=1000

# Compaction
compaction.threshold=4

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus